# Generated by Django 5.1.2 on 2024-11-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('prevention', models.JSONField()),
                ('treatment', models.JSONField()),
            ],
            options={
                'db_table': 'predict',
            },
        ),
        migrations.DeleteModel(
            name='LeafDisease',
        ),
    ]
